#!/usr/bin/env tsx
/**
 * form-1to1-audit.ts
 *
 * forms-map.json 의 PDF 원본을 텍스트 추출 → auto/{docId}.md 와 필드명 매칭률 검증.
 * 결과: docId 별 매칭률 + 누락 필드 보고서 (markdown).
 *
 * 의존: 시스템 `pdftotext` (poppler) — macOS: brew install poppler
 *
 * 실행:
 *   npx tsx scripts/quality/form-1to1-audit.ts
 *
 * 산출:
 *   scripts/quality/form-1to1-audit-report.md
 */
import { readFileSync, existsSync, writeFileSync } from "node:fs";
import { resolve, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..", "..");
const FORMS_MAP_PATH = resolve(ROOT, "src", "ontology", "forms", "forms-map.json");
const FORMS_DIR = resolve(ROOT, "src", "ontology", "forms");
const AUTO_DIR = resolve(FORMS_DIR, "auto");
const REPORT_PATH = resolve(ROOT, "scripts", "quality", "form-1to1-audit-report.md");

interface FormEntry {
  formId: string;
  docId: string;
  title: string;
  filename: string;
  format: "pdf" | "hwp" | "hwpx" | "xlsx" | "md";
  autoGenerated?: boolean;
}

interface AuditResult {
  docId: string;
  formId: string;
  format: string;
  title: string;
  pdfFieldCount: number;
  autoFieldCount: number;
  matched: number;
  matchRate: number;
  missingInAuto: string[]; // PDF 에 있으나 auto 에 안 보이는 후보
}

// PDF 텍스트 추출 — pdftotext -layout 으로 표 구조 보존 시도
function extractPdfText(pdfPath: string): string | null {
  const r = spawnSync("pdftotext", ["-layout", "-enc", "UTF-8", pdfPath, "-"], {
    encoding: "utf8",
    maxBuffer: 16 * 1024 * 1024,
  });
  if (r.status !== 0) return null;
  return r.stdout || "";
}

// 텍스트에서 핵심 필드명 후보 추출
// 휴리스틱: 길이 2~28 + 마크다운/공백 노이즈 제외 + 한국어 표제어 우선
function extractCandidateFields(text: string): string[] {
  const fields = new Set<string>();
  const lines = text.split(/\r?\n+/);
  for (const raw of lines) {
    const line = raw.trim().replace(/\s+/g, " ");
    if (!line) continue;
    // 길이 가드
    if (line.length < 2 || line.length > 28) continue;
    // 마크다운/표 구분자 제외
    if (/^[#>|\-*=_~`]+$/.test(line)) continue;
    // 숫자/날짜만은 제외
    if (/^[\d\s./:-]+$/.test(line)) continue;
    // URL/이메일 제외
    if (/(https?:\/\/|@|\.com|\.kr)/i.test(line)) continue;
    // 영문/기호만 (한글 0개) 짧은 라벨 제외 — 우리는 한국어 양식에 집중
    if (!/[가-힣]/.test(line)) continue;
    fields.add(line);
  }
  return [...fields];
}

// auto/.md 본문에 PDF 필드 후보가 매칭되는지 (부분 문자열)
function matchAgainst(field: string, autoText: string): boolean {
  const f = field.replace(/[()*?():·.,]/g, "").trim();
  if (!f) return false;
  // 양식 핵심 단어가 .md 본문에 등장하는지
  return autoText.includes(f);
}

function main(): void {
  const formsMap = JSON.parse(readFileSync(FORMS_MAP_PATH, "utf8"));
  const arr: FormEntry[] =
    (formsMap as { forms?: FormEntry[] }).forms ||
    (formsMap as { entries?: FormEntry[] }).entries ||
    (Array.isArray(formsMap) ? (formsMap as FormEntry[]) : []);

  const targets = arr.filter((f) => f.format === "pdf");
  console.log(`[audit] PDF 대상 ${targets.length}건 (총 formId ${arr.length})`);

  const results: AuditResult[] = [];

  for (const f of targets) {
    const pdfPath = join(FORMS_DIR, f.filename);
    if (!existsSync(pdfPath)) {
      console.warn(`[skip] ${f.formId} — PDF 미존재: ${pdfPath}`);
      continue;
    }
    const autoPath = join(AUTO_DIR, `${f.docId}.md`);
    if (!existsSync(autoPath)) {
      console.warn(`[skip] ${f.formId} — auto/.md 미존재: ${f.docId}.md`);
      continue;
    }

    const pdfText = extractPdfText(pdfPath);
    if (pdfText === null) {
      console.warn(`[fail] ${f.formId} — pdftotext 실패`);
      continue;
    }
    const autoText = readFileSync(autoPath, "utf8");

    const pdfFields = extractCandidateFields(pdfText);
    const autoFields = extractCandidateFields(autoText);

    const matched = pdfFields.filter((p) => matchAgainst(p, autoText));
    const missing = pdfFields.filter((p) => !matched.includes(p));

    results.push({
      docId: f.docId,
      formId: f.formId,
      format: f.format,
      title: f.title,
      pdfFieldCount: pdfFields.length,
      autoFieldCount: autoFields.length,
      matched: matched.length,
      matchRate: pdfFields.length ? matched.length / pdfFields.length : 0,
      missingInAuto: missing.slice(0, 25),
    });
  }

  // 매칭률 낮은 순
  results.sort((a, b) => a.matchRate - b.matchRate);

  // 보고서 markdown 생성
  const avg = results.length
    ? results.reduce((sum, r) => sum + r.matchRate, 0) / results.length
    : 0;

  const lines: string[] = [];
  lines.push("# 양식 1:1 대조 보고서 (PDF 원본 ↔ auto/{docId}.md)");
  lines.push("");
  lines.push(
    `> 생성: ${new Date().toISOString()} · PDF 대조 ${results.length}건 · 평균 매칭률 **${(avg * 100).toFixed(1)}%**`,
  );
  lines.push("");
  lines.push("매칭률 = PDF 에서 추출한 한국어 필드명 후보가 auto/.md 본문에 등장하는 비율");
  lines.push("");
  lines.push("## 매칭률 요약 (낮은 순)");
  lines.push("");
  lines.push("| # | 매칭률 | docId | formId | PDF 필드 | auto 필드 | matched |");
  lines.push("|---:|---:|---|---|---:|---:|---:|");
  results.forEach((r, i) => {
    lines.push(
      `| ${i + 1} | ${(r.matchRate * 100).toFixed(1)}% | \`${r.docId}\` | \`${r.formId}\` | ${r.pdfFieldCount} | ${r.autoFieldCount} | ${r.matched} |`,
    );
  });
  lines.push("");

  lines.push("## 누락 필드 상세 (PDF 에는 있으나 auto/.md 에 안 보이는 단어)");
  lines.push("");
  for (const r of results) {
    if (r.missingInAuto.length === 0) continue;
    lines.push(`### \`${r.docId}\` — ${(r.matchRate * 100).toFixed(1)}%`);
    lines.push("");
    lines.push(`> ${r.title}`);
    lines.push("");
    for (const m of r.missingInAuto) lines.push(`- \`${m}\``);
    lines.push("");
  }

  writeFileSync(REPORT_PATH, lines.join("\n"), "utf8");
  console.log(`\n✅ 보고서: ${REPORT_PATH}`);
  console.log(`   평균 매칭률: ${(avg * 100).toFixed(1)}% (총 ${results.length}건)`);
}

main();
