#!/usr/bin/env tsx
/**
 * add-construction-docs.ts
 * 건설안전 특화 의무문서 12개 추가 — 기준규칙 + KOSHA 권장 양식 기반.
 * 모두 requiredFields/reviewRules/applicableWhen 충실 (CARV 4/4 통과).
 */
import { writeFile } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const DOCS = resolve(__dirname, "..", "..", "src", "ontology", "graph", "nodes", "documents");
const FETCHED = "2026-04-28";

interface ConstructionDoc {
  id: string; docId: string; file: string; title: string; cycle: string;
  alternativeNames?: string[]; description: string; trigger: string;
  applicableWhen: { appliesTo: string; scaleNotes: string };
  exemptedWhen?: { reasons: string[] };
  legalBasis: string[]; guidedBy?: string[];
  requiredFields: Array<{ key: string; label: string; source: string }>;
  reviewRules: Array<{ rule: string; severity: "blocker" | "warning"; legalBasis: string }>;
}

const DOCS_LIST: ConstructionDoc[] = [
  {
    id: "doc:weekly/scaffolding_inspection_checklist",
    docId: "scaffolding_inspection_checklist",
    file: "scaffolding-inspection-checklist.jsonld",
    title: "비계 안전점검표 (강관·시스템·달비계)",
    alternativeNames: ["비계 점검일지","Scaffolding Daily Check"],
    cycle: "cyc:weekly",
    description: "기준규칙 §59~§71 비계 작업 시 매일·강풍·강우 후 안전점검. 강관비계·시스템비계·달비계·말비계·이동식비계 구분. KOSHA Guide C-30·C-D-1 권장 양식.",
    trigger: "비계 설치·해체·변경 시 + 매일 작업 시작 전 + 강풍(10m/s 이상)·강우(우중) 작업 후",
    applicableWhen: { appliesTo: "applic:all_workplace", scaleNotes: "비계 사용 모든 건설현장." },
    exemptedWhen: { reasons: ["비계 미사용 (지상 1.5m 미만 작업)"] },
    legalBasis: ["art:기준규칙:59","art:기준규칙:60","art:기준규칙:62","art:기준규칙:63","art:기준규칙:65","art:기준규칙:67","art:기준규칙:71"],
    guidedBy: ["doc:kosha_guide/C-30-2024","doc:kosha_guide/C-31-2024"],
    requiredFields: [
      { key: "siteInfo",         label: "현장명·작업위치·점검일자", source: "기준규칙 §59" },
      { key: "scaffoldType",     label: "비계 종류 (강관/시스템/달/말/이동식)", source: "기준규칙 §59-65" },
      { key: "scaffoldDimension", label: "비계 규격 (높이·폭·층수)",  source: "기준규칙 §62" },
      { key: "footingCheck",     label: "기둥·기초 점검 (밑받침·고정·수평)", source: "기준규칙 §60" },
      { key: "tiebackCheck",     label: "벽 연결 (Tieback) 간격·강도", source: "기준규칙 §63" },
      { key: "guardrailCheck",   label: "안전난간 설치 (상부·중간·발끝막이)", source: "기준규칙 §13" },
      { key: "platformCheck",    label: "작업발판 (폭 40cm 이상·틈새 3cm 이하·고정)", source: "기준규칙 §56" },
      { key: "ladderCheck",      label: "승강설비 (사다리·승강로) 설치", source: "기준규칙 §65" },
      { key: "loadCheck",        label: "적재하중 표시 + 초과 여부",     source: "기준규칙 §62" },
      { key: "weatherCheck",     label: "기상조건 (강풍·강우·강설 시 작업 중지)", source: "기준규칙 §38" },
      { key: "deteriorationCheck", label: "부재 변형·부식·균열·손상",  source: "기준규칙 §61" },
      { key: "inspector",        label: "점검자 (관리감독자) 서명",   source: "기준규칙 §35" },
    ],
    reviewRules: [
      { rule: "필수 — 안전난간 + 작업발판 + 벽연결 3종 점검", severity: "blocker", legalBasis: "art:기준규칙:59" },
      { rule: "필수 — 적재하중 표시 + 초과 시 작업 중지", severity: "blocker", legalBasis: "art:기준규칙:62" },
      { rule: "필수 — 강풍 10m/s 또는 강우 시 작업 중지", severity: "blocker", legalBasis: "art:기준규칙:38" },
      { rule: "권고 — 점검 사진 첨부 (요주의 부위)", severity: "warning", legalBasis: "art:기준규칙:35" },
    ],
  },
  {
    id: "doc:daily/fall_prevention_net_inspection",
    docId: "fall_prevention_net_inspection",
    file: "fall-prevention-net-inspection.jsonld",
    title: "추락방지망 (안전방망) 점검표",
    cycle: "cyc:daily",
    description: "기준규칙 §42-§45 추락방지 의무. 안전방망 설치·점검. KOSHA Guide C-3 권장 양식. 그물코·인장강도·설치각도·경사 점검.",
    trigger: "안전방망 설치 후 + 매일 작업 시작 전 + 충격 받은 후",
    applicableWhen: { appliesTo: "applic:all_workplace", scaleNotes: "추락 위험 2m 이상 작업." },
    legalBasis: ["art:기준규칙:42","art:기준규칙:43","art:기준규칙:44","art:기준규칙:45"],
    guidedBy: ["doc:kosha_guide/C-3-2024"],
    requiredFields: [
      { key: "installLocation",   label: "설치 위치·층·면적", source: "기준규칙 §42" },
      { key: "netSpec",           label: "그물코 (10cm 이내) + 매듭 강도",  source: "기준규칙 §44" },
      { key: "tensileStrength",   label: "인장강도 시험 결과 (kN)",    source: "기준규칙 §44" },
      { key: "installAngle",      label: "설치 각도 (수평 + 처짐)",   source: "기준규칙 §43" },
      { key: "supportPoint",      label: "지지점 강도·간격",            source: "기준규칙 §43" },
      { key: "damageCheck",       label: "손상·변색·노화 점검",         source: "기준규칙 §45" },
      { key: "edgeProtection",    label: "끝단 보호 + 갭 0",            source: "기준규칙 §43" },
      { key: "inspector",         label: "점검자 서명",                 source: "기준규칙 §35" },
    ],
    reviewRules: [
      { rule: "필수 — 그물코 10cm 이내 + 인장강도 검사 결과", severity: "blocker", legalBasis: "art:기준규칙:44" },
      { rule: "필수 — 충격 받은 망은 즉시 교체 또는 재시험",   severity: "blocker", legalBasis: "art:기준규칙:45" },
    ],
  },
  {
    id: "doc:monthly/safety_harness_inspection",
    docId: "safety_harness_inspection",
    file: "safety-harness-inspection.jsonld",
    title: "안전대 (Full Body Harness) 점검 대장",
    cycle: "cyc:monthly",
    description: "산안법 §38 + 기준규칙 §32 보호구 지급·관리. 추락방지용 안전대 정기 점검. KOSHA Guide C-44 권장 양식.",
    trigger: "안전대 지급 시 + 매월 정기 점검 + 추락 충격 후",
    applicableWhen: { appliesTo: "applic:all_workplace", scaleNotes: "추락 위험 2m 이상 작업 종사자." },
    legalBasis: ["art:기준규칙:32","art:기준규칙:42","art:산안법:38"],
    guidedBy: ["doc:kosha_guide/C-44-2024"],
    requiredFields: [
      { key: "harnessId",         label: "안전대 고유번호 + 사용자",   source: "기준규칙 §32" },
      { key: "model",             label: "제조사·모델·인증번호 (KCs)", source: "산안법 §83" },
      { key: "manufactureDate",   label: "제조일 + 사용기한 (3년)",   source: "산안법 §83" },
      { key: "webbing",           label: "웨빙 (마모·절단·곰팡이)",   source: "기준규칙 §32" },
      { key: "buckle",            label: "버클·D-ring (변형·균열)",   source: "기준규칙 §32" },
      { key: "lanyard",           label: "랜야드·충격흡수장치 (절단·인장)", source: "기준규칙 §42" },
      { key: "snapHook",          label: "후크 (자동잠금·스프링·이중잠금)", source: "기준규칙 §42" },
      { key: "fallExperience",    label: "추락 충격 이력 (있으면 즉시 폐기)", source: "기준규칙 §42" },
      { key: "inspector",         label: "점검자 + 다음 점검일",      source: "기준규칙 §32" },
    ],
    reviewRules: [
      { rule: "필수 — KCs 인증 + 사용기한 3년 이내", severity: "blocker", legalBasis: "art:산안법:83" },
      { rule: "필수 — 추락 충격 받은 안전대는 즉시 폐기", severity: "blocker", legalBasis: "art:기준규칙:42" },
      { rule: "필수 — 웨빙·버클·랜야드·후크 4종 점검", severity: "blocker", legalBasis: "art:기준규칙:32" },
    ],
  },
  {
    id: "doc:monthly/temporary_fire_facility_check",
    docId: "temporary_fire_facility_check",
    file: "temporary-fire-facility-check.jsonld",
    title: "임시소방시설 설치·점검표 (건설현장)",
    cycle: "cyc:monthly",
    description: "건설현장 임시소방시설 (소화기·간이소화장치·비상경보·간이피난유도선·비상조명·방화포). 소방시설법 §15 + 화재안전기준 NFSC 401-7. KOSHA C-113 취약시기 관리.",
    trigger: "공사 착공 + 매월 정기 점검 + 화기작업 전",
    applicableWhen: { appliesTo: "applic:construction_50bn_plus", scaleNotes: "건설공사 면적 5천㎡ 이상 또는 지상 11층 이상." },
    legalBasis: ["art:기준규칙:236","art:기준규칙:237","art:기준규칙:238","art:기준규칙:239","art:기준규칙:240"],
    guidedBy: ["doc:kosha_guide/C-113-2020"],
    requiredFields: [
      { key: "siteInfo",          label: "현장명·면적·층수·공정률", source: "소방시설법 §15" },
      { key: "extinguisher",      label: "소화기 (능력단위·설치수·위치)",   source: "NFSC 401-7" },
      { key: "simpleExtinguisher", label: "간이소화장치 (수원 4m³+호스)",   source: "NFSC 401-7" },
      { key: "fireAlarm",         label: "비상경보장치 (배터리·작동)",      source: "NFSC 401-7" },
      { key: "evacuationLine",    label: "간이피난유도선 (축광·연속)",      source: "NFSC 401-7" },
      { key: "emergencyLight",    label: "비상조명 (작동·예비전원)",        source: "NFSC 401-7" },
      { key: "fireBlanket",       label: "방화포 (용접 작업장 + 저장)",     source: "기준규칙 §240" },
      { key: "evacuationRoute",   label: "피난동선 (장애물·표지)",          source: "기준규칙 §428" },
      { key: "inspector",         label: "점검자 서명",                    source: "소방시설법 §15" },
    ],
    reviewRules: [
      { rule: "필수 — 소화기 + 비상경보 + 비상조명 3종 설치 + 작동", severity: "blocker", legalBasis: "art:기준규칙:236" },
      { rule: "필수 — 화기작업 전 방화포 + 소화기 비치", severity: "blocker", legalBasis: "art:기준규칙:240" },
      { rule: "권고 — 매월 점검 사진 첨부", severity: "warning", legalBasis: "art:기준규칙:35" },
    ],
  },
  {
    id: "doc:daily/construction_machinery_inspection",
    docId: "construction_machinery_inspection",
    file: "construction-machinery-inspection.jsonld",
    title: "건설기계 일일점검표 (굴삭기·로더·덤프트럭·롤러)",
    cycle: "cyc:daily",
    description: "기준규칙 §78~§116 건설기계 안전. 운전 시작 전 일일점검. KOSHA Guide C-G-21 권장 양식. 굴삭기·로더·덤프트럭·롤러·콘크리트펌프·믹서트럭·크레인 운반차 등.",
    trigger: "운전 시작 전 매일",
    applicableWhen: { appliesTo: "applic:all_workplace", scaleNotes: "건설기계 사용 모든 현장." },
    legalBasis: ["art:기준규칙:78","art:기준규칙:79","art:기준규칙:38","annex:기준규칙:별표4-3호"],
    requiredFields: [
      { key: "machineId",         label: "기계 고유번호·종류·기종", source: "기준규칙 §78" },
      { key: "operator",          label: "운전자 (자격·면허·경력)",     source: "기준규칙 §86" },
      { key: "engineCheck",       label: "엔진 (오일·냉각수·연료)",     source: "기준규칙 §79" },
      { key: "hydraulicCheck",    label: "유압장치 (호스·실린더·유량)", source: "기준규칙 §79" },
      { key: "brakeCheck",        label: "제동장치 (작동·간격)",        source: "기준규칙 §79" },
      { key: "tireTrackCheck",    label: "타이어·궤도 (마모·압력)",     source: "기준규칙 §79" },
      { key: "lightSignal",       label: "전조등·후진경보·경광등",      source: "기준규칙 §79" },
      { key: "rops",              label: "전도방지장치 (ROPS)·캐빈",   source: "기준규칙 §198" },
      { key: "fopsCheck",         label: "낙하물보호구조 (FOPS)",       source: "기준규칙 §198" },
      { key: "loadCapacity",      label: "정격하중·작업범위 표시",       source: "기준규칙 §79" },
      { key: "inspector",         label: "운전자 + 관리감독자 서명",     source: "기준규칙 §35" },
    ],
    reviewRules: [
      { rule: "필수 — 운전자 자격증 + 일일점검 서명", severity: "blocker", legalBasis: "art:기준규칙:86" },
      { rule: "필수 — 제동·후진경보·전도방지 3종 작동", severity: "blocker", legalBasis: "art:기준규칙:79" },
      { rule: "필수 — 정격하중 초과 작업 금지", severity: "blocker", legalBasis: "art:기준규칙:79" },
    ],
  },
  {
    id: "doc:daily/tower_crane_inspection",
    docId: "tower_crane_inspection",
    file: "tower-crane-inspection.jsonld",
    title: "타워크레인 일일점검표",
    cycle: "cyc:daily",
    description: "기준규칙 §142 타워크레인 안전. 운전 시작 전 일일점검 + 강풍 후 + 정기점검(매월). KOSHA Guide C-21 권장 양식.",
    trigger: "운전 시작 전 매일 + 강풍 10m/s 이상 후 + 매월 정기점검",
    applicableWhen: { appliesTo: "applic:all_workplace", scaleNotes: "타워크레인 사용 모든 건설현장." },
    legalBasis: ["art:기준규칙:142","annex:기준규칙:별표4-1호","art:산안법:93"],
    guidedBy: ["doc:kosha_guide/C-21-2024","doc:kosha_guide/C-39-2024"],
    requiredFields: [
      { key: "craneId",           label: "타워크레인 고유번호·기종·정격하중", source: "산안법 §93" },
      { key: "operator",          label: "운전자 (타워크레인 면허)",   source: "기준규칙 §142" },
      { key: "structureCheck",    label: "구조부 (마스트·지브·카운터지브 균열·변형)", source: "기준규칙 §142" },
      { key: "hoistRopeCheck",    label: "와이어로프 (마모·소선절단·꼬임 — 폐기기준)", source: "기준규칙 §63" },
      { key: "boltCheck",         label: "체결볼트 (토크 + 조임 표시)", source: "기준규칙 §142" },
      { key: "limitSwitch",       label: "권과방지장치·과부하방지장치 작동", source: "기준규칙 §134" },
      { key: "wind",              label: "풍속 측정 + 작업 가능 여부 (10m/s 미만)", source: "기준규칙 §38" },
      { key: "anchorage",         label: "기초·앵커·지지대 (수직도·기울기)", source: "기준규칙 §142" },
      { key: "signaler",          label: "신호수 배치 + 무전기",       source: "기준규칙 §40" },
      { key: "safetyDevice",      label: "비상정지장치 + 운전실 보호",  source: "기준규칙 §134" },
      { key: "inspector",         label: "운전자 + 관리감독자 서명",   source: "기준규칙 §35" },
    ],
    reviewRules: [
      { rule: "필수 — 권과·과부하 방지장치 작동", severity: "blocker", legalBasis: "art:기준규칙:134" },
      { rule: "필수 — 풍속 10m/s 이상 작업 중지", severity: "blocker", legalBasis: "art:기준규칙:38" },
      { rule: "필수 — 와이어로프 폐기기준 점검", severity: "blocker", legalBasis: "art:기준규칙:63" },
      { rule: "필수 — 신호수 배치 + 안전인증서 부착", severity: "blocker", legalBasis: "art:기준규칙:40" },
    ],
  },
  {
    id: "doc:ad_hoc/formwork_shoring_drawing",
    docId: "formwork_shoring_drawing",
    file: "formwork-shoring-drawing.jsonld",
    title: "거푸집동바리 시공상세도",
    cycle: "cyc:ad_hoc",
    description: "기준규칙 §331~§337 거푸집동바리 작업. 시공상세도 + 구조계산서 + 작업계획서. KOSHA Guide C-9 권장 양식.",
    trigger: "거푸집동바리 시공 전 (구조검토 + 도면 작성 + 결재)",
    applicableWhen: { appliesTo: "applic:all_workplace", scaleNotes: "수직 콘크리트 타설 시 동바리 사용 모든 현장." },
    legalBasis: ["art:기준규칙:331","art:기준규칙:332","art:기준규칙:333","art:기준규칙:334","art:기준규칙:335","art:기준규칙:336","art:기준규칙:337","annex:기준규칙:별표4"],
    guidedBy: ["doc:kosha_guide/C-9-2024","doc:kosha_guide/C-25-2024"],
    requiredFields: [
      { key: "siteInfo",          label: "현장명·층·구조물명",           source: "기준규칙 §38" },
      { key: "concreteVolume",    label: "콘크리트 타설량·타설속도",      source: "KCS 14 20 12" },
      { key: "formworkType",      label: "거푸집 종류 (합판·시스템·알폼)", source: "기준규칙 §331" },
      { key: "shoringType",       label: "동바리 종류 (강관·시스템·알루미늄)", source: "기준규칙 §332" },
      { key: "structuralCalc",    label: "구조계산 (자중·시공·풍하중·편심)", source: "기준규칙 §332" },
      { key: "spacing",           label: "동바리 간격·수평재 간격",       source: "기준규칙 §333" },
      { key: "verticality",       label: "수직도 + 기울기 허용오차",      source: "기준규칙 §332" },
      { key: "footing",           label: "받침판 + 지반 침하 방지",      source: "기준규칙 §332" },
      { key: "bracing",           label: "수평·경사 가새 (X자) 설치",    source: "기준규칙 §333" },
      { key: "removalCondition",  label: "콘크리트 강도 도달 후 해체",    source: "기준규칙 §337" },
      { key: "designer",          label: "설계자 (구조기술사) 서명",     source: "건설기술진흥법 §39" },
      { key: "supervisor",        label: "현장 관리감독자 결재",         source: "기준규칙 §35" },
    ],
    reviewRules: [
      { rule: "필수 — 구조계산서 + 시공상세도 결재", severity: "blocker", legalBasis: "art:기준규칙:332" },
      { rule: "필수 — 동바리 수평재 + 경사 가새 (X자) 설치", severity: "blocker", legalBasis: "art:기준규칙:333" },
      { rule: "필수 — 콘크리트 압축강도 도달 전 해체 금지", severity: "blocker", legalBasis: "art:기준규칙:337" },
    ],
  },
  {
    id: "doc:ad_hoc/concrete_placement_plan",
    docId: "concrete_placement_plan",
    file: "concrete-placement-plan.jsonld",
    title: "콘크리트 타설 시공계획서",
    cycle: "cyc:ad_hoc",
    description: "기준규칙 §38 + KCS 14 20 10 콘크리트 타설 시공계획. 타설 순서·속도·양생·관리감독자·신호체계. 거푸집동바리 시공상세도와 함께 작성.",
    trigger: "콘크리트 타설 24시간 전 (관리감독자 결재 + 사전점검)",
    applicableWhen: { appliesTo: "applic:all_workplace", scaleNotes: "RC구조물 타설 모든 현장." },
    legalBasis: ["art:기준규칙:38","art:기준규칙:331","art:기준규칙:332"],
    guidedBy: ["doc:kosha_guide/C-9-2024"],
    requiredFields: [
      { key: "placementZone",     label: "타설 구획 + 면적·물량",       source: "KCS 14 20 10" },
      { key: "placementSpeed",    label: "타설 속도 (m/h) — 거푸집 압력", source: "기준규칙 §332" },
      { key: "placementOrder",    label: "타설 순서 (도면 표시)",       source: "KCS 14 20 10" },
      { key: "pumpPosition",      label: "콘크리트펌프카 위치·이동경로", source: "기준규칙 §38" },
      { key: "vibratorPlan",      label: "다짐장비 (진동기) 위치·인원", source: "KCS 14 20 10" },
      { key: "weatherCheck",      label: "기상 (기온 0~30℃ · 강우 시 중지)", source: "KCS 14 20 10" },
      { key: "curing",            label: "양생 방법 (보온·습윤·강도시험)", source: "KCS 14 20 10" },
      { key: "shoringRemoval",    label: "동바리 해체 시기 (강도 도달)", source: "기준규칙 §337" },
      { key: "signalSystem",      label: "신호체계·통신 (무전기·신호수)", source: "기준규칙 §40" },
      { key: "emergencyStop",     label: "비상시 중지 절차",            source: "기준규칙 §38" },
      { key: "supervisor",        label: "관리감독자 결재 + 작업자 명단", source: "기준규칙 §35" },
    ],
    reviewRules: [
      { rule: "필수 — 타설 속도 거푸집 측압 한계 이내", severity: "blocker", legalBasis: "art:기준규칙:332" },
      { rule: "필수 — 강우 시 작업 중지 + 양생 계획", severity: "blocker", legalBasis: "art:기준규칙:38" },
      { rule: "필수 — 동바리 해체 강도 시험 후", severity: "blocker", legalBasis: "art:기준규칙:337" },
    ],
  },
  {
    id: "doc:ad_hoc/earth_retaining_drawing",
    docId: "earth_retaining_drawing",
    file: "earth-retaining-drawing.jsonld",
    title: "흙막이 가시설 시공상세도",
    cycle: "cyc:ad_hoc",
    description: "기준규칙 §340~§346 굴착 작업. 2m 이상 굴착 + 흙막이 시공상세도 + 계측계획. KOSHA Guide C-22 + KCS 21 30 00.",
    trigger: "굴착 깊이 2m 이상 + 시공 착수 전",
    applicableWhen: { appliesTo: "applic:all_workplace", scaleNotes: "굴착 깊이 2m 이상 모든 토목·건축 현장." },
    legalBasis: ["art:기준규칙:340","art:기준규칙:341","art:기준규칙:342","art:기준규칙:343","art:기준규칙:344","art:기준규칙:345","art:기준규칙:346","annex:기준규칙:별표4-6호"],
    guidedBy: ["doc:kosha_guide/C-22-2024","doc:kosha_guide/C-58-2024"],
    requiredFields: [
      { key: "siteInfo",          label: "현장명·굴착 깊이·면적",        source: "기준규칙 §340" },
      { key: "soilSurvey",        label: "지반조사 결과 (N치·지하수위·토층)", source: "기준규칙 §340" },
      { key: "retainingType",     label: "흙막이 종류 (CIP·SCW·시트파일·H-pile)", source: "KCS 21 30 00" },
      { key: "structuralCalc",    label: "구조계산 (안정성·근입깊이·버팀대 강도)", source: "기준규칙 §340" },
      { key: "drainagePlan",      label: "배수계획 (지하수 유입 대책)",   source: "기준규칙 §346" },
      { key: "monitoringPlan",    label: "계측계획 (변위·응력·지하수위·인접 건물)", source: "KCS 21 30 00" },
      { key: "instrumentList",    label: "계측기 종류·개수·설치위치",     source: "KCS 21 30 00" },
      { key: "actionLevel",       label: "관리기준치 (1차·2차·3차)",   source: "KCS 21 30 00" },
      { key: "emergencyResponse", label: "비상조치 (관리기준 초과 시)",   source: "기준규칙 §340" },
      { key: "designer",          label: "설계자 (토목구조기술사) 서명", source: "건설기술진흥법 §39" },
    ],
    reviewRules: [
      { rule: "필수 — 지반조사 + 구조계산 결재", severity: "blocker", legalBasis: "art:기준규칙:340" },
      { rule: "필수 — 계측계획 + 관리기준치 + 비상조치", severity: "blocker", legalBasis: "art:기준규칙:340" },
      { rule: "필수 — 인접 건물 영향 평가 + 사전 통보", severity: "blocker", legalBasis: "art:기준규칙:340" },
    ],
  },
  {
    id: "doc:weekly/temporary_electric_inspection",
    docId: "temporary_electric_inspection",
    file: "temporary-electric-inspection.jsonld",
    title: "가설전기 점검표 (분전반·접지·누전차단)",
    cycle: "cyc:weekly",
    description: "기준규칙 §301~§305 전기작업 + 가설전기 안전. 분전반·접지·누전차단기·가설배선 점검. KOSHA Guide C-G-32 권장.",
    trigger: "가설전기 설치 + 매주 정기점검 + 강우 후",
    applicableWhen: { appliesTo: "applic:all_workplace", scaleNotes: "건설현장 가설전기 사용 모든 현장." },
    legalBasis: ["art:기준규칙:301","art:기준규칙:302","art:기준규칙:303","art:기준규칙:304","art:기준규칙:305","art:기준규칙:319"],
    requiredFields: [
      { key: "siteInfo",          label: "현장명·가설전기 용량 (kVA)", source: "기준규칙 §301" },
      { key: "panelCheck",        label: "분전반 (잠금·표지·누전차단기)", source: "기준규칙 §304" },
      { key: "groundingCheck",    label: "접지 (저항 100Ω 이하)",     source: "기준규칙 §302" },
      { key: "elcb",              label: "누전차단기 (작동·시험)",      source: "기준규칙 §304" },
      { key: "wiringCheck",       label: "가설배선 (피복·통로·매설)",   source: "기준규칙 §301" },
      { key: "weatherProof",      label: "방수·방습 (옥외 + IP 등급)",  source: "기준규칙 §301" },
      { key: "loto",              label: "전기작업 LOTO 절차 + 시건", source: "기준규칙 §319" },
      { key: "qualifiedPerson",   label: "전기담당 (전기기사 + 자격증)", source: "기준규칙 §301" },
      { key: "inspector",         label: "점검자 + 관리감독자 서명",   source: "기준규칙 §35" },
    ],
    reviewRules: [
      { rule: "필수 — 누전차단기 작동 + 매주 시험", severity: "blocker", legalBasis: "art:기준규칙:304" },
      { rule: "필수 — 접지저항 100Ω 이하", severity: "blocker", legalBasis: "art:기준규칙:302" },
      { rule: "필수 — 강우 후 즉시 점검 + 옥외 방수", severity: "blocker", legalBasis: "art:기준규칙:301" },
      { rule: "필수 — 활선 작업 시 LOTO + 검전 후 작업", severity: "blocker", legalBasis: "art:기준규칙:319" },
    ],
  },
  {
    id: "doc:ad_hoc/signaler_appointment",
    docId: "signaler_appointment",
    file: "signaler-appointment.jsonld",
    title: "신호수 지정서·교육이수 기록",
    cycle: "cyc:ad_hoc",
    description: "기준규칙 §40 + §142 크레인·차량계 건설기계 신호수 지정. 교육 8시간 이상 이수 + 신호기·무전기 지급.",
    trigger: "건설기계·크레인·중량물 인양 작업 시작 전",
    applicableWhen: { appliesTo: "applic:all_workplace", scaleNotes: "크레인·타워크레인·중량물 인양·차량계 건설기계 사용 작업." },
    legalBasis: ["art:기준규칙:40","art:기준규칙:142","art:기준규칙:79"],
    requiredFields: [
      { key: "operationType",     label: "작업 종류 (인양·운반·반출입)", source: "기준규칙 §40" },
      { key: "signalerName",      label: "신호수 성명·소속",           source: "기준규칙 §40" },
      { key: "trainingRecord",    label: "신호수 교육 8시간 이수증",    source: "산안법 §29" },
      { key: "signalCode",        label: "표준수신호 (KOSHA Guide C-67)", source: "기준규칙 §40" },
      { key: "communicationGear", label: "무전기·호각·신호기 지급",     source: "기준규칙 §40" },
      { key: "operatorPair",      label: "운전자 - 신호수 1:1 매칭",    source: "기준규칙 §40" },
      { key: "supervisor",        label: "관리감독자 지정 + 결재",      source: "기준규칙 §35" },
    ],
    reviewRules: [
      { rule: "필수 — 신호수 8시간 교육 이수증 첨부", severity: "blocker", legalBasis: "art:산안법:29" },
      { rule: "필수 — 표준수신호 + 무전기 지급", severity: "blocker", legalBasis: "art:기준규칙:40" },
      { rule: "필수 — 운전자 - 신호수 1:1 매칭", severity: "blocker", legalBasis: "art:기준규칙:40" },
    ],
  },
  {
    id: "doc:ad_hoc/aerial_work_platform_plan",
    docId: "aerial_work_platform_plan",
    file: "aerial-work-platform-plan.jsonld",
    title: "고소작업대 사용계획서",
    cycle: "cyc:ad_hoc",
    description: "기준규칙 §30 고소작업대(차량탑재형 + 시저리프트 + 붐리프트). 사용 전 작업계획 + 자격자 + 안전대 착용.",
    trigger: "고소작업대 사용 작업 시작 전",
    applicableWhen: { appliesTo: "applic:all_workplace", scaleNotes: "2m 이상 고소작업대 사용 모든 현장." },
    legalBasis: ["art:기준규칙:30","art:산안법:38"],
    guidedBy: ["doc:kosha_guide/A-G-2-2025"],
    requiredFields: [
      { key: "platformType",      label: "기종 (시저/붐/차량탑재) + 정격하중", source: "기준규칙 §30" },
      { key: "workArea",          label: "작업 위치·높이·범위",          source: "기준규칙 §30" },
      { key: "operatorQual",      label: "운전자 자격 (3톤 이상 면허·교육)", source: "기준규칙 §86" },
      { key: "harnessCheck",      label: "안전대 착용 + 후크 결속",      source: "기준규칙 §32" },
      { key: "groundCheck",       label: "지반 안정성 (수평·내력)",       source: "기준규칙 §30" },
      { key: "outrigger",         label: "아우트리거 전개·고정",          source: "기준규칙 §30" },
      { key: "windCheck",         label: "풍속 10m/s 이상 작업 중지",     source: "기준규칙 §38" },
      { key: "limitSwitch",       label: "비상정지·과부하방지장치",      source: "기준규칙 §30" },
      { key: "supervisor",        label: "관리감독자 지정",              source: "기준규칙 §35" },
    ],
    reviewRules: [
      { rule: "필수 — 운전자 자격 + 안전대 결속 + 아우트리거", severity: "blocker", legalBasis: "art:기준규칙:30" },
      { rule: "필수 — 풍속 10m/s 이상 작업 중지", severity: "blocker", legalBasis: "art:기준규칙:38" },
    ],
  },
];

(async () => {
  let written = 0;
  for (const d of DOCS_LIST) {
    const path = resolve(DOCS, d.file);
    const obj = {
      "@context": "../../context.jsonld",
      "@id": d.id,
      "@type": ["Document", "DigitalDocument"],
      docId: d.docId,
      title: d.title,
      ...(d.alternativeNames && { alternativeNames: d.alternativeNames }),
      description: d.description,
      cycle: d.cycle,
      trigger: d.trigger,
      applicableWhen: d.applicableWhen,
      ...(d.exemptedWhen && { exemptedWhen: d.exemptedWhen }),
      legalBasis: d.legalBasis,
      ...(d.guidedBy && { guidedBy: d.guidedBy }),
      requiredFields: d.requiredFields,
      reviewRules: d.reviewRules,
      verificationStatus: "verified",
      _meta: {
        publishedBy: "라텔웍스 + 황룡건설(주)",
        fetchedAt: FETCHED,
        licenseHint: "저작권법 §7 비보호 (자유 인용)",
        scope: "construction",
        note: "건설안전 특화 의무문서 (Phase 3 wave1 — 기준규칙 + KCS + KOSHA C 시리즈 권장 양식 통합)."
      }
    };
    await writeFile(path, JSON.stringify(obj, null, 2) + "\n", "utf-8");
    written++;
  }
  console.log(`✅ ${written} 건설안전 특화 의무문서 추가 (CARV 4/4)`);
})();
